### PR TITLE
Add run on repl.it badge to README

### PR DESCRIPTION
**Pull request by hackerboy9**
This pull request adds a  badge to the . This will allow users to easily run this repository in their browser, without having to set up an environment. You can learn more about Repl.it [here](https://repl.it).

### CODE REVIEW

**Comment by AEFeinstein** [comment]
You clearly didn't test this, as https://repl.it/github/fofix/fofix is nowhere near working. I suspect this is [hactoberfest spam](https://hacktoberfest.digitalocean.com/faq)

> As a maintainer, how should I handle spam pull requests?
>
> We dislike seeing spam pull requests just as much as you, so please give them an **invalid** or **spam** label and close them. Pull requests that contain a label with the word invalid or spam won’t be counted toward Hacktoberfest.

**Comment by Linkid** [comment]
Hi @hackerboy9 ! Thank you for you contribution.

Please, read the [contributing guide](https://github.com/fofix/fofix/blob/master/CONTRIBUTING.md) before making a PR.
Here are my comments:
- your commit message is not right (you can see [the Travis job](https://travis-ci.org/github/fofix/fofix/jobs/733382232#L475))
- our project still use python 2, not python 3 (feel free to have a look at the [README](https://github.com/fofix/fofix/blob/master/README.md) ;))
- the config file seems to be generated by importing this repo into Repl.it. It does not run anything… Maybe you should custom it.

@AEFeinstein : maybe, maybe not. Anyway, this PR doesn't count for the Hacktoberfest as is. Let's see how it starts off ;).

**Comment by AEFeinstein** [comment]
I may have jumped a conclusion here, though @hackerboy9 did make an _identical_ PR to https://github.com/dickreuter/Poker/pull/109

**Comment by Linkid** [comment]
No answer, I'm closing this PR. Thank you @AEFeinstein for the link.

**Pull request closed without merging**
