### PR TITLE
Split main game code from launcher

### PR DESCRIPTION
**Pull request by alvanson**
I have attempted to separate "initialization" code from the game's main loop (object). This has the advantage of simplifying `FoFiX.py` by reducing the interleaving of module imports, function definitions and executable code before the `if __name__ == '__main__':` line. My thought is that module initialization (e.g. parsing command-line arguments, disabling OpenGL error checking, setting up logging) would happen in `FoFiX.py` (what I've been calling the "launcher"), keeping the new `Main` module more game-related.

This pull request also includes some minor code cleanups to the affected files. Note that the three `__future__` imports are suggested by the [Python 3 Porting Guide](https://docs.python.org/3/howto/pyporting.html) to ensure consistent behaviour of imports, `print` and division between Py2 & Py3.

### CODE REVIEW

**Comment by alvanson** [comment]
Did you want me to rebase this pull request on latest master?

**Comment by Linkid** [comment]
Thanks for the PR. Yes, please, rebase with master.

**Comment by Linkid** [comment]
Hi @alvanson.
I would like to merge your PR but it needs to be rebased first. Can I do it or do you plan to do it  ?
Thanks.

**Comment by Linkid** [comment]
At last, I took care of it. Thanks for your contribution :).

**Pull request merged**
