### PR TITLE
Clean up the README

### PR DESCRIPTION
**Pull request by Linkid**
Simplify the README

### CODE REVIEW

**Comment by mdsitton** [comment]
Hey one suggestion. I'd link to the fretwork readme when mentioning installation via pip:
https://github.com/fofix/fretwork/blob/master/README.md

**Comment by mdsitton** [comment]
Also RunFofFromSources.bat isnt actually going to work with it now located in the scripts folder, so i'd make the run instructions the same for both linux and windows.

**Comment by mdsitton** [comment]
Basically if you navigate to the scripts folder and try to run the script its not going to work (which is what most windows users will probably try to do)

Also the full path for that script is wrong, but if its removed from the readme then it doesnt matter anymore :P

**Comment by Linkid** [comment]
Ok, thanks for your comments. I'll change some parts.

**Pull request merged**
