### PR TITLE
Fixup credit display, add myself.

### PR DESCRIPTION
**Pull request by wrzwicky**
Fix credit screen to actually display credits. There were a number of display bugs, plus the CREDITS file was not displayed.

### CODE REVIEW

**Comment by Linkid** [comment]
Thanks for the split. Please, rebase your commits into one, and I'll be able to merge it :).

**Comment by wrzwicky** [comment]
I don't understand the request; commits are able to be merged now.  And the Travis error is due to gitlint, and I can't fix git commit messages (git won't let you edit old messages).

**Comment by Linkid** [comment]
I would like you to rebase your two commits into one, because making 2 commits just to remove what you added in the first one is useless. If you search in the internet, you'll find some good posts (like this one : https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request). Yes, it is a force push, but it is a good one.
And about Travis, you should run tests *before* pushing to avoid to break it ;). Read contributor guidelines, please.

**Comment by wrzwicky** [comment]
Neither of those things are necessary or appropriate. My 2nd commit does more than just just remove things from the first commit, so squashing is not appropriate. And rebasing is not necessary since GitHub reports this PR can be merged.

Re. Travis: I keep an eye on the reported errors, and they've all been gitlint bugs, mostly gitlint disapproving of trailing punctuation, which is a bug since English sentences end with punctuation. But I'll  see if I can get gitlint into my git process.

**Comment by Linkid** [comment]
"Do not end the subject line with a period" (from [CONTRIBUTING.md](https://github.com/fofix/fofix/blob/master/CONTRIBUTING.md#git-commit-guidelines), [How to Write a Git Commit Message](https://chris.beams.io/posts/git-commit/#end) and [Travis](https://travis-ci.org/fofix/fofix/jobs/296061091#L483)) : you do not finish a title by a point ;).

**Comment by wrzwicky** [comment]
Title, got it. That makes way more sense than the verbose posting you referenced.

But commit message can't be changed, (or at least, is not worth the effort just for punctuation) and the other items don't need to be changed. What now?

**Comment by mdsitton** [comment]
I think its fine to merge this as-is. I'm willing to give some leeway for those just getting into things, as long as they are aware of things for the future.

**Comment by mdsitton** [comment]
And as @wrzwicky said the commits are totally separate things logically. I see no need to merge the commits.

**Pull request merged**
