### PR TITLE
Add contributing guidelines

### PR DESCRIPTION
**Pull request by Linkid**
As a GPL-licensed software, contributions are welcomed. Then adding guidelines could be useful.

### CODE REVIEW

**Comment by wrzwicky** [comment]
Re. CONTRIBUTING.md:
There's one thing I'd love clarified that I haven't found discussed anywhere. Assume I've finished one topic (done some hacks, checked in, and made a pull request). What do I do for my **second** topic? Do I branch off my branch, or do I need to go back and branch off of _master_, thereby losing the benefit of my first hack?  I think it's worth putting this in the CONTRIBUTING file for people new to multi-user Git (like me :).

Also, please add a section on coding style, e.g. No trailing spaces; no tabs; 4 spaces per indent; which docstring system to use.  Basically if you request a style-related change to anyone's pull request, add a copy to CONTRIBUTING for future developers. Thanks!

**Comment by mdsitton** [comment]
@wrzwicky Generally you want to always branch off of master so the pull requests say self contained.

If you want to work on a continuous branch, you could then construct pull requests by cherry picking the commits you want for it into a branch directly off master.

I do think you should resubmit your current pull requests via via that method before we merge them.
@Linkid thoughts?

**Comment by wrzwicky** [comment]
Re. branching: That's what I (eventually) figured, but I didn't see it discussed anywhere online, which is why I suggested it be mentioned in CONTRIBUTING. 

Re. my own pull requests:  Should be discussed under them, not here. Post anywhere, I monitor them all. :D

**Comment by Linkid** [comment]
Hi!
Thanks for reviews! I think it's important to build those guidelines together.
I'll add a part about branching. There are a lot of contributing guidelines with the process of branching, so it seems to be classic. I'll do it this week ;).

**Comment by Linkid** [comment]
I added git commit guidelines (with refs) and a quick commit style guide (which seems obvious).

**Comment by wrzwicky** [comment]
I found another donation for the style guide, along with the author:

> commit ba4b2e101ca5e934efad270055557eaa781b80b5
> Author: John Stumpo <stump@jstump.com> 2012-07-16 01:17:04
> 
> Reindent all Python and Cython source to four-space indents.
> 
> The tool used for this also removed all trailing whitespace and all
> trailing blank lines from said files, and ensured that they have a
> newline at the end.
> 
> Please try to preserve these properties.

**Comment by Linkid** [comment]
Some of it is already written in the PEP8. This is why the style guide is not huge ;).

**Pull request merged**
