### PR TITLE
Pin dependencies

### PR DESCRIPTION
**Pull request by alvanson**
The dependencies listed in `requirements.txt` (including dependencies of dependencies, etc) should be explicitly pinned to specific versions. This makes all environments (dev, test, freeze) predictable, repeatable and deterministic.

The versions selected in this pull request are those from Debian 9 which is what I'm successfully running FoFiX master on (+ patches from my 'stabilize' branch/pull request #105). The idea is to start with a known-good set of pinned dependencies and, when required, update from there after testing new versions.

**Note:** `pip install -r requirements.txt` doesn't quite work in a fresh environment as it tries to build `fretwork` before everything else. I've had to remove the last line (fretwork) from the file, run `pip install -r requirements.txt` (actually, to address #104, I run `pip install --no-binary -r requirements.txt`) then `pip install https://github.com/fofix/fretwork/archive/0.2.0.tar.gz`.

### CODE REVIEW

**Comment by Linkid** [comment]
Thank you for your PR :).

I think you can use last version of each dependencies ;).

**Comment by alvanson** [comment]
I think we should still be pinning them; I just put in versions I know work. Did you want me to update my pull request with new versions?

**Comment by Linkid** [comment]
Yes, you should update versions to use the latest. Then, it will be good for a merge.
And if you can do that in only one commit (by amending the first one), it will be great :).
Thanks.

**Comment by alvanson** [comment]
Done. Versions are latest as of today.

**Comment by Linkid** [comment]
Good, I merged it. You can delete your branch safely :).

**Pull request merged**
