### PR TITLE
Remove SVN and googlecode refs

### PR DESCRIPTION
**Pull request by Linkid**

### CODE REVIEW

**Comment by mdsitton** [comment]
Just a note you really shouldn't be removing lines from the copyright header as those people still technically have copyright claim  over whatever code they may have added to the file. So its not a great idea imo.

**Comment by mdsitton** [comment]
Also please keep the year in the copyright headers :)

**Comment by Linkid** [comment]
I think names should not be in the header of each file. but gathered in the AUTHOR file. By the way, I'm workin on it.

**Comment by Linkid** [comment]
Ok, I let names in headers

**Pull request merged**
