### PR TITLE
WIP: fix to launch the one-shot mode

### PR DESCRIPTION
**Pull request by Linkid**
WIP

### CODE REVIEW

**Comment by mdsitton** [comment]
How's the progress on this?

**Comment by Linkid** [comment]
I'm still working on it. But I'm busy those days with my intership, so I didn't have much time to look at it :(.
Right now, some attributes are not initialized in the Song class, so there is only a black screen.

**Comment by mdsitton** [comment]
Just thought i'd go ahead and ask here, since every day i keep missing you on irc...

So any progress since your last update in irc?

**Comment by mdsitton** [comment]
Ill ask again any plans to continue with this? If not I may look at the issue myself when I get finished cleaning up the guitarscene.

**Comment by Linkid** [comment]
Hi! Sorry to have disappeared like that… I don't have enough time right know to continue this. If you want to look at it, you can do it.

**Comment by mdsitton** [comment]
alright, ill just close this then.

**Pull request closed without merging**
