### PR TITLE
Fix issue #21, plus docs.

### PR DESCRIPTION
**Pull request by wrzwicky**
Fix issue #21, plus docs.

### CODE REVIEW

**Comment by Linkid** [comment]
Thanks for your PR :). I'll review it as soon as possible.

Please, make your PR from the `master` branch to avoid duplicated commits.

**Comment by Linkid** [comment]
Moreover, could you split your commit into logical unit ones, and taking a look at http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html for your commit message ;).

**Comment by wrzwicky** [comment]
- Re. Branching from _master_:  Sorry, I didn't know the workflow, and in all the help pages I found online, noone mentioned that issue. I'll do that on future patches.
- Re. "Logical units":  Sorry about that also, I didn't realize how dumb that was til after it was done.  At this point, _no_, I can't "split" the commit because the commit is already done. I'd have to make a new branch and reproduce that work in the new branch.  But is it really that important? Do you want to merge only some of the commits?  Because I'd rather spend my time working on other bugs.  :^)

**Comment by Linkid** [comment]
Hi!

About branching, it is usual to create a topic branch from _master_. Even if your commits in the other branch are relevant, separate them to new ones is important and make reviews easier than combining all of them ;).
In your case, you can take a look at this [rebase comment on StackOverflow](https://stackoverflow.com/a/23744569/5222966). I thnk it's easy to do it here.

About logical commits, it's really important, I think. You'll see that everywhere. It is very useful for backporting, reviewing or just for history (`git blame`, …).
In your case, you should take a look at [the git manual about splitting commits with rebase](https://git-scm.com/docs/git-rebase.html#_splitting_commits). I think it's easy enough and you do will not waste your time by doing it ;).

As you see, rebasing is really helpful. In your case, I'll start with the _master_ branch issue. Then, with splitting commits into small ones. But if you think it's to hard, either I can help you (in IRC), or I can just close this PR for you to start a new one.

**Comment by wrzwicky** [comment]
Rebuilt as #97.

**Pull request closed without merging**
